language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - ci/before_install

# command to install dependencies
install:
  - sudo apt-get install binutils gdal-bin libproj-dev postgresql-9.1-postgis
  - pip install -r requirements.txt --use-mirrors

before_script:
  - psql -c 'create database project;' -U postgres

# command to run tests
script: publicmeeting/manage.py test

# the settings module requires a few environment variables
env:
  SECRET_KEY=123abc
  TWITTER_CONSUMER_KEY=abcxyz
  TWITTER_CONSUMER_SECRET=987123


notifications:
  irc:
    channels:
      - "irc.freenode.org#civicworks"
    on_success: change
    on_failure: always
  email: false
