language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - ci/before_install

# command to install dependencies
install: pip install -r requirements.txt --use-mirrors

# command to run tests
script: nosetests


notifications:
  irc:
    channels:
      - "irc.freenode.org#civicworks"
    on_success: change
    on_failure: always
  email: false
