#!/bin/sh

# Get node and install it locally
if [ ! `node -v` ]
then
  wget "http://nodejs.org/dist/v0.6.12/node-v0.6.12.tar.gz"

  tar -xzf "node-v0.6.12.tar.gz"

  cd node*
  ./configure
  make

  cd node*  # the install dumps you back out of the node* dir.
  export PATH=$PATH;"`pwd`/out/Release"  # node is in here.

  cd ..
fi

# Get npm and install it locally
if [ ! `npm -v` ]
then
  mkdir npm
  cd npm

  curl "http://npmjs.org/install.sh" | npm_config_prefix=`pwd` sh

  export PATH=$PATH;"`pwd`/bin"  # npm is in here.

  cd ..
fi

npm install less
export PATH=$PATH;"`pwd`/node_modules/.bin"  # lessc is in here.
